"""Build web/arrival-template.js from arrival loading-screen screenshots.

Usage: python scripts/build_arrival_template.py --name 도시 [--region x0,x1,y0,y1] shot1.webp shot2.webp shot3.webp

--region is the pixel box (in the screenshot) that contains only the title block;
the default fits the city loading screen, the village popup uses 10,160,36,75.

Each screenshot must be a window capture of the game at the same size with the
title text (for example "도시 / 입항 중입니다.") in the top-left corner. Bright,
low-saturation pixels that are white in every screenshot are taken as the text
mask, so backgrounds that differ between screenshots cancel out. A ring 2-3 px
outside the text is stored as the "ring" mask that must stay dark.

The module holds a list of named templates; running the script again with the
same --name replaces that entry and keeps the others. The screenshots are not
stored in the repository. Requires Pillow and NumPy.
"""
import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image
from numpy.lib.stride_tricks import sliding_window_view

REGION = (15, 180, 40, 150)  # x0, x1, y0, y1 search box in the reference capture
LUMA, SAT = 215, 50
TARGET = Path("web/arrival-template.js")


def dilate(m, r):
    if r == 0:
        return m
    p = np.pad(m, r)
    return sliding_window_view(p, (2 * r + 1, 2 * r + 1)).any(axis=(-1, -2))


def rle(mask):
    flat = mask.ravel().astype(np.uint8)
    runs, cur, n = [], 0, 0
    for v in flat:
        if v == cur:
            n += 1
        else:
            runs.append(n)
            cur = v
            n = 1
    runs.append(n)
    return runs


def build(name, paths, region=REGION):
    frames = [np.asarray(Image.open(p).convert("RGB")).astype(int) for p in paths]
    assert len({f.shape for f in frames}) == 1, "screenshots must share one size"
    h, w = frames[0].shape[:2]
    x0, x1, y0, y1 = region
    masks = []
    for a in frames:
        l = (a[..., 0] * 299 + a[..., 1] * 587 + a[..., 2] * 114) // 1000
        s = a.max(-1) - a.min(-1)
        masks.append(((l > LUMA) & (s < SAT))[y0:y1, x0:x1])
    text = np.logical_and.reduce(masks)
    ys, xs = np.where(text)
    by0, by1, bx0, bx1 = ys.min() - 3, ys.max() + 4, xs.min() - 3, xs.max() + 4
    text = text[by0:by1, bx0:bx1]
    ring = dilate(text, 3) & ~dilate(text, 1)
    return {"name": name, "refWidth": w, "refHeight": h, "originX": int(x0 + bx0), "originY": int(y0 + by0),
            "width": int(text.shape[1]), "height": int(text.shape[0]),
            "textCount": int(text.sum()), "ringCount": int(ring.sum()),
            "text": rle(text), "ring": rle(ring)}


def load_existing():
    if not TARGET.exists():
        return []
    body = TARGET.read_text(encoding="utf-8").split("export default", 1)[1].strip().rstrip(";")
    data = json.loads(body)
    return data if isinstance(data, list) else [data]


def main(argv):
    name, region = "도시", REGION
    while argv[:1] in (["--name"], ["--region"]):
        if argv[0] == "--name":
            name = argv[1]
        else:
            region = tuple(int(v) for v in argv[1].split(","))
        argv = argv[2:]
    if not argv:
        sys.exit(__doc__)
    out = build(name, argv, region)
    templates = [t for t in load_existing() if t["name"] != name] + [out]
    js = ("// Generated by scripts/build_arrival_template.py. Do not edit by hand.\n"
          "// Masks are run-length encoded row-major, starting with a run of 0s.\n"
          "export default " + json.dumps(templates, ensure_ascii=False, separators=(",", ":")) + ";\n")
    TARGET.write_text(js, encoding="utf-8")
    print(f"{name}: {out['width']}x{out['height']} at ({out['originX']},{out['originY']}) "
          f"text={out['textCount']} ring={out['ringCount']}; {len(templates)} template(s) in module")


if __name__ == "__main__":
    main(sys.argv[1:])
